# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

shop1 = Shop.create!(name: 'Castorama')
Schedule.create!(day: 'Monday', opening_time: '08:00', closing_time: '12:00', shop: shop1)
Schedule.create!(day: 'Monday', opening_time: '14:00', closing_time: '19:00', shop: shop1)
Schedule.create!(day: 'Tuesday', opening_time: '08:00', closing_time: '12:00', shop: shop1)
Schedule.create!(day: 'Tuesday', opening_time: '14:00', closing_time: '19:00', shop: shop1)
Schedule.create!(day: 'Wednesday', opening_time: '08:00', closing_time: '12:00', shop: shop1)
Schedule.create!(day: 'Wednesday', opening_time: '14:00', closing_time: '16:00', shop: shop1)
Schedule.create!(day: 'Thursday', opening_time: '08:00', closing_time: '12:00', shop: shop1)
Schedule.create!(day: 'Thursday', opening_time: '14:00', closing_time: '19:00', shop: shop1)
Schedule.create!(day: 'Friday', opening_time: '08:00', closing_time: '12:00', shop: shop1)
Schedule.create!(day: 'Friday', opening_time: '14:00', closing_time: '19:00', shop: shop1)
Schedule.create!(day: 'Saturday', opening_time: '08:00', closing_time: '12:00', shop: shop1)
Schedule.create!(day: 'Saturday', opening_time: '14:00', closing_time: '16:00', shop: shop1)

shop2 = Shop.create!(name: 'Bricorama')
Schedule.create!(day: 'Monday', opening_time: '08:00', closing_time: '12:00', shop: shop2)
Schedule.create!(day: 'Monday', opening_time: '14:00', closing_time: '19:00', shop: shop2)
Schedule.create!(day: 'Tuesday', opening_time: '08:00', closing_time: '12:00', shop: shop2)
Schedule.create!(day: 'Tuesday', opening_time: '14:00', closing_time: '19:00', shop: shop2)
Schedule.create!(day: 'Wednesday', opening_time: '08:00', closing_time: '12:00', shop: shop2)
Schedule.create!(day: 'Wednesday', opening_time: '14:00', closing_time: '16:00', shop: shop2)
Schedule.create!(day: 'Thursday', opening_time: '08:00', closing_time: '12:00', shop: shop2)
Schedule.create!(day: 'Thursday', opening_time: '14:00', closing_time: '19:00', shop: shop2)
Schedule.create!(day: 'Friday', opening_time: '08:00', closing_time: '12:00', shop: shop2)
Schedule.create!(day: 'Friday', opening_time: '14:00', closing_time: '19:00', shop: shop2)
Schedule.create!(day: 'Saturday', opening_time: '08:00', closing_time: '12:00', shop: shop2)
Schedule.create!(day: 'Saturday', opening_time: '14:00', closing_time: '16:00', shop: shop2)

shop3 = Shop.create!(name: 'Mr Bricolage')
Schedule.create!(day: 'Monday', opening_time: '08:00', closing_time: '12:00', shop: shop3)
Schedule.create!(day: 'Monday', opening_time: '14:00', closing_time: '19:00', shop: shop3)
Schedule.create!(day: 'Tuesday', opening_time: '08:00', closing_time: '12:00', shop: shop3)
Schedule.create!(day: 'Tuesday', opening_time: '14:00', closing_time: '19:00', shop: shop3)
Schedule.create!(day: 'Wednesday', opening_time: '08:00', closing_time: '12:00', shop: shop3)
Schedule.create!(day: 'Wednesday', opening_time: '14:00', closing_time: '16:00', shop: shop3)
Schedule.create!(day: 'Thursday', opening_time: '08:00', closing_time: '12:00', shop: shop3)
Schedule.create!(day: 'Thursday', opening_time: '14:00', closing_time: '19:00', shop: shop3)
Schedule.create!(day: 'Friday', opening_time: '08:00', closing_time: '12:00', shop: shop3)
Schedule.create!(day: 'Friday', opening_time: '14:00', closing_time: '19:00', shop: shop3)
Schedule.create!(day: 'Saturday', opening_time: '08:00', closing_time: '12:00', shop: shop3)
Schedule.create!(day: 'Saturday', opening_time: '14:00', closing_time: '16:00', shop: shop3)

shop4 = Shop.create!(name: 'Leroy Merlin')
Schedule.create!(day: 'Monday', opening_time: '08:00', closing_time: '12:00', shop: shop4)
Schedule.create!(day: 'Monday', opening_time: '14:00', closing_time: '19:00', shop: shop4)
Schedule.create!(day: 'Tuesday', opening_time: '08:00', closing_time: '12:00', shop: shop4)
Schedule.create!(day: 'Tuesday', opening_time: '14:00', closing_time: '19:00', shop: shop4)
Schedule.create!(day: 'Wednesday', opening_time: '08:00', closing_time: '12:00', shop: shop4)
Schedule.create!(day: 'Wednesday', opening_time: '14:00', closing_time: '16:00', shop: shop4)
Schedule.create!(day: 'Thursday', opening_time: '08:00', closing_time: '12:00', shop: shop4)
Schedule.create!(day: 'Thursday', opening_time: '14:00', closing_time: '19:00', shop: shop4)
Schedule.create!(day: 'Friday', opening_time: '08:00', closing_time: '12:00', shop: shop4)
Schedule.create!(day: 'Friday', opening_time: '14:00', closing_time: '19:00', shop: shop4)
Schedule.create!(day: 'Saturday', opening_time: '08:00', closing_time: '12:00', shop: shop4)
Schedule.create!(day: 'Saturday', opening_time: '14:00', closing_time: '16:00', shop: shop4)
